Build editor
emmyobonyo/notes pull request #1
Opened 2022-03-15 10:26 UTC by emmyobonyo

### Tasks completed
- Build the Editor of the Notes App.

2022-03-15 10:31 UTC, emmyobonyo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Design editor](https://trello.com/c/yoRlRqeC/18-design-editor)

2022-03-17 08:07 UTC, KnightWorker37 requested changes

2022-03-17 08:07 UTC, KnightWorker37 commented on src/components/Sidebar.js
> +
@emmyobonyo This should be it's own component

```suggestion

function NoteTile({note, index, currentNoteId, setCurrentNoteId}) {
return (<div key={note.id}>
            <div
                className={`title ${
                    note.id === currentNoteId ? "selected-note" : ""
                }`}
                onClick={() => setCurrentNoteId(note.id)}
            >
                <h4 className="text-snippet">Note {index + 1}</h4>
            </div>
        </div>);
}

export default function Sidebar({ notes, currentNote, newNote, setCurrentNoteId }) {

```

2022-03-17 08:07 UTC, KnightWorker37 commented on src/components/Sidebar.js
> +                <button className="new-note" onClick={props.newNote}>+</button>
```suggestion
                <button className="new-note" onClick={newNote}>+</button>
```

2022-03-17 08:07 UTC, KnightWorker37 commented on src/components/Sidebar.js
> +            {noteElements}
```suggestion
            {notes.map((note, index) => <NoteTile key={note.id} note={note} index=>{index} currentNoteId={currentNote.id} setCurrentNoteId={setCurrentNoteId} />}
```

2022-04-07 16:10 UTC, emmyobonyo commented on src/App.js
> +    }
Understood. To be honest, this was a guided project so I was mainly following the directions of the Tutor, but I understand what you're putting across. I also think he decided to do it this way since some of the results from the logic were being passed as props to both children. So he decided to put them in the parent (App.js).

2022-04-07 16:10 UTC, emmyobonyo commented on src/App.test.js
> -test('renders learn react link', () => {
👍

2022-04-07 16:13 UTC, emmyobonyo commented on src/components/Sidebar.js
> +
I believe it is. It's the `sidebar` component.

2022-05-28 09:13 UTC, merged