Give Notes a custom titile
emmyobonyo/notes pull request #3
Opened 2022-03-15 15:33 UTC by emmyobonyo

- Notes can now have a custom title.

2022-03-15 15:34 UTC, emmyobonyo commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create custom titles for notes](https://trello.com/c/7cnsBloU/16-create-custom-titles-for-notes)

2022-03-17 08:15 UTC, KnightWorker37 requested changes

2022-03-17 08:15 UTC, KnightWorker37 commented on src/App.js
> +        for(let i = 0; i < oldNotes.length; i++) {
@emmyobonyo as I mentioned before: should separate concerns

2022-04-07 16:20 UTC, emmyobonyo commented on src/App.js
> +        for(let i = 0; i < oldNotes.length; i++) {
Understood.

2022-05-28 09:13 UTC, merged